In [1]:
import pandas as pd
import numpy as np

In [3]:
#22,45,88,5,12,123.

In [4]:
entrada = input("escribe los numeros: ")

escribe los numeros: 22,45,88,5,12,123


In [5]:
print(entrada)
print(type(entrada))

22,45,88,5,12,123
<class 'str'>


In [7]:
numeros = entrada.split(",")

In [8]:
print(type(numeros))
print(numeros)

<class 'list'>
['22', '45', '88', '5', '12', '123']


In [3]:
import pandas as pd
from sklearn import datasets
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
# Cargar datos. Vamos a utilizar el conjunto de datos 
diccionario = datasets.load_breast_cancer()
diccionario


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [5]:
# Imprimir los valores del diccionario
for key, value in diccionario.items():
    print(key, value)
# Acceder a un valor específico del diccionario
print(diccionario['DESCR'])

data [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
target [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 

In [6]:
 lista = ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

 for i, item in enumerate(lista):
    print(i, item)

0 mean radiusmean texturemean perimetermean areamean smoothnessmean compactnessmean concavitymean concave pointsmean symmetrymean fractal dimensionradius errortexture errorperimeter errorarea errorsmoothness errorcompactness errorconcavity errorconcave points errorsymmetry errorfractal dimension errorworst radiusworst textureworst perimeterworst areaworst smoothnessworst compactnessworst concavityworst concave pointsworst symmetryworst fractal dimension


In [7]:
# accedo a las "keys": diccionario.keys()
df_target = pd.DataFrame.from_dict(diccionario["target"])
df_data = pd.DataFrame.from_dict(diccionario["data"])
df_target = df_target.rename(columns={0: "class"})
df = pd.concat([df_data,df_target], axis=1)
df

0      1       2       3        4        5        6        7       8  \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

           9  ...     21      22      23       24       25      26      27  \
0    0.07871  ...  17.33  184.60  2019.0  0.16220  0.66560  0.7119  0.2654   
1    0.05667  ...  23.41  158.80  1956.0  0.12380  0.18660  0.2416  0.1860   
2    0.05999  ...  25.53  152.50  1709.0  0.14440  0.42450  0.4504  0.2430   
3    0.09744  ...  26.50   98.87   567.7  0.20980  0.86630  0.6869  0.2575   
4    0.05883  ...  16.67  152.20  1575.0  0.13740  0.20500  0.4000  0.1625   
..       ...  ...    ...     ...     ...      ...      ...     ...     ...   
564  0.05623  ...  26.40  166.10  2027.0  0.14100  0.21130  0.4107  0.2216   
565  0.05533  ...  38.25  155.00  1731.0  0.11660  0.19220  0.3215  0.1628   
566  0.05648  ...  34.12  126.70  1124.0  0.11390  0.30940  0.3403  0.1418   
567  0.07016  ...  39.42  184.60  1821.0  0.16500  0.86810  0.9387  0.2650   
568  0.05884  ...  30.37   59.16   268.6  0.08996  0.06444  0.0000  0.0000   

         28       29  class  
0    0.4601  0.11890      0  
1    0.2750  0.08902      0  
2    0.3613  0.08758      0  
3    0.6638  0.17300      0  
4    0.2364  0.07678      0  
..      ...      ...    ...  
564  0.2060  0.07115      0  
565  0.2572  0.06637      0  
566  0.2218  0.07820      0  
567  0.4087  0.12400      0  
568  0.2871  0.07039      1  

[569 rows x 31 columns]

In [8]:
# Lista con los nuevos nombres de las columnas
new_columns = ['mean radius', 'mean texture', 'mean perimeter', 'mean area',
               'mean smoothness', 'mean compactness', 'mean concavity',
               'mean concave points', 'mean symmetry', 'mean fractal dimension',
               'radius error', 'texture error', 'perimeter error', 'area error',
               'smoothness error', 'compactness error', 'concavity error',
               'concave points error', 'symmetry error', 'fractal dimension error',
               'worst radius', 'worst texture', 'worst perimeter', 'worst area',
               'worst smoothness', 'worst compactness', 'worst concavity',
               'worst concave points', 'worst symmetry', 'worst fractal dimension']

# Renombrar las columnas del dataframe
df = df.rename(columns=dict(zip(df.columns, new_columns)))

In [9]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['class'], axis=1), df['class'], test_size=0.3, random_state=0)
params = {
    'objective': 'multi:softmax',
    'num_class': 3,
    'max_depth': 3,
    'eta': 0.1,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'eval_metric': 'mlogloss',
    'seed': 0
}

# Se utiliza la sintaxis de doble asterisco ** para desempaquetar un diccionario
# y pasar sus valores como argumentos de palabras clave a una función. Esto es
# útil cuando se tienen muchos parámetros y se desea pasarlos en un diccionario
# para hacer el código más legible y fácil de mantener.
model = XGBClassifier(**params)
model.fit(X_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, early_stopping_rounds=None,
              enable_categorical=False, eta=0.1, eval_metric='mlogloss',
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_class=3, num_parallel_tree=None, ...)

In [11]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [12]:
# Sacamos por pantalla los datos de test, junto con la predicción, los resultados esperados y booleano de acierto
df_test = X_test

In [13]:
df['class']

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: class, Length: 569, dtype: int32

In [14]:
df['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

In [15]:
df_test["real"] = df['class'][X_test.index]
df_test["real"]

512    0
457    1
439    1
298    1
37     1
      ..
7      0
408    0
523    1
361    1
553    1
Name: real, Length: 171, dtype: int32

In [16]:
df_test["real"].value_counts()

1    108
0     63
Name: real, dtype: int64

In [17]:
df_test[df_test["real"] > 0]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
457       13.210         25.25           84.10      537.9          0.08791   
439       14.020         15.66           89.59      606.5          0.07966   
298       14.260         18.17           91.22      633.1          0.06576   
37        13.030         18.42           82.61      523.8          0.08983   
515       11.340         18.61           72.76      391.2          0.10490   
..           ...           ...             ...        ...              ...   
440       10.970         17.20           71.73      371.5          0.08915   
137       11.430         15.39           73.06      399.8          0.09639   
523       13.710         18.68           88.73      571.0          0.09916   
361       13.300         21.57           85.24      546.1          0.08582   
553        9.333         21.94           59.01      264.0          0.09240   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
457           0.05205         0.02772              0.02068         0.1619   
439           0.05581         0.02087              0.02652         0.1589   
298           0.05220         0.02475              0.01374         0.1635   
37            0.03766         0.02562              0.02923         0.1467   
515           0.08499         0.04302              0.02594         0.1927   
..                ...             ...                  ...            ...   
440           0.11130         0.09457              0.03613         0.1489   
137           0.06889         0.03503              0.02875         0.1734   
523           0.10700         0.05385              0.03783         0.1714   
361           0.06373         0.03344              0.02424         0.1815   
553           0.05605         0.03996              0.01282         0.1692   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
457                 0.05584  ...          34.23            91.29       632.9   
439                 0.05586  ...          19.31            96.53       688.9   
298                 0.05586  ...          25.26           105.80       819.7   
37                  0.05863  ...          22.81            84.46       545.9   
515                 0.06211  ...          23.03            79.15       478.6   
..                      ...  ...            ...              ...         ...   
440                 0.06640  ...          26.87            90.14       476.4   
137                 0.05865  ...          22.02            79.93       462.0   
523                 0.06843  ...          25.63            99.43       701.9   
361                 0.05696  ...          29.20            92.94       621.2   
553                 0.06576  ...          25.05            62.86       295.8   

     worst smoothness  worst compactness  worst concavity  \
457           0.12890            0.10630          0.13900   
439           0.10340            0.10170          0.06260   
298           0.09445            0.21670          0.15650   
37            0.09701            0.04619          0.04833   
515           0.14830            0.15740          0.16240   
..                ...                ...              ...   
440           0.13910            0.40820          0.47790   
137           0.11900            0.16480          0.13990   
523           0.14250            0.25660          0.19350   
361           0.11400            0.16670          0.12120   
553           0.11030            0.08298          0.07993   

     worst concave points  worst symmetry  worst fractal dimension  real  
457               0.06005          0.2444                  0.06788     1  
439               0.08216          0.2136                  0.06710     1  
298               0.07530          0.2636                  0.07676     1  
37                0.05013          0.1987                  0.06169     1  
515               0.08542          0.3060                  0.06783     1  

In [19]:
df_test = df_test.dropna(axis=0)
df_test["real"]

512    0
457    1
439    1
298    1
37     1
      ..
7      0
408    0
523    1
361    1
553    1
Name: real, Length: 171, dtype: int32

In [20]:
df_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
512       13.400         20.52           88.64      556.7          0.11060   
457       13.210         25.25           84.10      537.9          0.08791   
439       14.020         15.66           89.59      606.5          0.07966   
298       14.260         18.17           91.22      633.1          0.06576   
37        13.030         18.42           82.61      523.8          0.08983   
..           ...           ...             ...        ...              ...   
7         13.710         20.83           90.20      577.9          0.11890   
408       17.990         20.66          117.80      991.7          0.10360   
523       13.710         18.68           88.73      571.0          0.09916   
361       13.300         21.57           85.24      546.1          0.08582   
553        9.333         21.94           59.01      264.0          0.09240   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
512           0.14690         0.14450              0.08172         0.2116   
457           0.05205         0.02772              0.02068         0.1619   
439           0.05581         0.02087              0.02652         0.1589   
298           0.05220         0.02475              0.01374         0.1635   
37            0.03766         0.02562              0.02923         0.1467   
..                ...             ...                  ...            ...   
7             0.16450         0.09366              0.05985         0.2196   
408           0.13040         0.12010              0.08824         0.1992   
523           0.10700         0.05385              0.03783         0.1714   
361           0.06373         0.03344              0.02424         0.1815   
553           0.05605         0.03996              0.01282         0.1692   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
512                 0.07325  ...          29.66           113.30       844.4   
457                 0.05584  ...          34.23            91.29       632.9   
439                 0.05586  ...          19.31            96.53       688.9   
298                 0.05586  ...          25.26           105.80       819.7   
37                  0.05863  ...          22.81            84.46       545.9   
..                      ...  ...            ...              ...         ...   
7                   0.07451  ...          28.14           110.60       897.0   
408                 0.06069  ...          25.41           138.10      1349.0   
523                 0.06843  ...          25.63            99.43       701.9   
361                 0.05696  ...          29.20            92.94       621.2   
553                 0.06576  ...          25.05            62.86       295.8   

     worst smoothness  worst compactness  worst concavity  \
512           0.15740            0.38560          0.51060   
457           0.12890            0.10630          0.13900   
439           0.10340            0.10170          0.06260   
298           0.09445            0.21670          0.15650   
37            0.09701            0.04619          0.04833   
..                ...                ...              ...   
7             0.16540            0.36820          0.26780   
408           0.14820            0.37350          0.33010   
523           0.14250            0.25660          0.19350   
361           0.11400            0.16670          0.12120   
553           0.11030            0.08298          0.07993   

     worst concave points  worst symmetry  worst fractal dimension  real  
512               0.20510          0.3585                  0.11090     0  
457               0.06005          0.2444                  0.06788     1  
439               0.08216          0.2136                  0.06710     1  
298               0.07530          0.2636                  0.07676     1  
37                0.05013          0.1987                  0.06169     1  

In [21]:
df_test["acierto"] = (y_pred == df_test["real"])
df_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
512       13.400         20.52           88.64      556.7          0.11060   
457       13.210         25.25           84.10      537.9          0.08791   
439       14.020         15.66           89.59      606.5          0.07966   
298       14.260         18.17           91.22      633.1          0.06576   
37        13.030         18.42           82.61      523.8          0.08983   
..           ...           ...             ...        ...              ...   
7         13.710         20.83           90.20      577.9          0.11890   
408       17.990         20.66          117.80      991.7          0.10360   
523       13.710         18.68           88.73      571.0          0.09916   
361       13.300         21.57           85.24      546.1          0.08582   
553        9.333         21.94           59.01      264.0          0.09240   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
512           0.14690         0.14450              0.08172         0.2116   
457           0.05205         0.02772              0.02068         0.1619   
439           0.05581         0.02087              0.02652         0.1589   
298           0.05220         0.02475              0.01374         0.1635   
37            0.03766         0.02562              0.02923         0.1467   
..                ...             ...                  ...            ...   
7             0.16450         0.09366              0.05985         0.2196   
408           0.13040         0.12010              0.08824         0.1992   
523           0.10700         0.05385              0.03783         0.1714   
361           0.06373         0.03344              0.02424         0.1815   
553           0.05605         0.03996              0.01282         0.1692   

     mean fractal dimension  ...  worst perimeter  worst area  \
512                 0.07325  ...           113.30       844.4   
457                 0.05584  ...            91.29       632.9   
439                 0.05586  ...            96.53       688.9   
298                 0.05586  ...           105.80       819.7   
37                  0.05863  ...            84.46       545.9   
..                      ...  ...              ...         ...   
7                   0.07451  ...           110.60       897.0   
408                 0.06069  ...           138.10      1349.0   
523                 0.06843  ...            99.43       701.9   
361                 0.05696  ...            92.94       621.2   
553                 0.06576  ...            62.86       295.8   

     worst smoothness  worst compactness  worst concavity  \
512           0.15740            0.38560          0.51060   
457           0.12890            0.10630          0.13900   
439           0.10340            0.10170          0.06260   
298           0.09445            0.21670          0.15650   
37            0.09701            0.04619          0.04833   
..                ...                ...              ...   
7             0.16540            0.36820          0.26780   
408           0.14820            0.37350          0.33010   
523           0.14250            0.25660          0.19350   
361           0.11400            0.16670          0.12120   
553           0.11030            0.08298          0.07993   

     worst concave points  worst symmetry  worst fractal dimension  real  \
512               0.20510          0.3585                  0.11090     0   
457               0.06005          0.2444                  0.06788     1   
439               0.08216          0.2136                  0.06710     1   
298               0.07530          0.2636                  0.07676     1   
37                0.05013          0.1987                  0.06169     1   
..                    ...             ...                      ...   ...   
7                 0.15560          0.3196                  0.11510     0   
408               0.1

In [22]:
df_test["acierto"].value_counts()

True     166
False      5
Name: acierto, dtype: int64

In [23]:
# Calcular la precisión del modelo en el conjunto de prueba
accuracy = (y_pred == y_test).sum() / len(y_test)
print(f"La precisión del modelo en el conjunto de prueba es: {accuracy:.2f}")

La precisión del modelo en el conjunto de prueba es: 0.97


In [24]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [25]:
y_test

512    0
457    1
439    1
298    1
37     1
      ..
7      0
408    0
523    1
361    1
553    1
Name: class, Length: 171, dtype: int32

In [26]:
confusion_matrix(y_test, y_pred)

array([[ 60,   3],
       [  2, 106]], dtype=int64)